from typing import Protocol
from uuid import UUID

from app.domain import Author, Download, Ebook, Manuscript, Sample


class AuthorRepository(Protocol):
    def add(self, author: Author) -> Author: ...
    def get(self, author_id: UUID) -> Author | None: ...
    def get_by_email(self, email: str) -> Author | None: ...
    def update(self, author: Author) -> Author: ...
    def delete(self, author_id: UUID) -> None: ...


class ManuscriptRepository(Protocol):
    def add(self, manuscript: Manuscript) -> Manuscript: ...
    def get(self, manuscript_id: UUID) -> Manuscript | None: ...
    def list_by_author(self, author_id: UUID) -> list[Manuscript]: ...
    def update(self, manuscript: Manuscript) -> Manuscript: ...
    def delete(self, manuscript_id: UUID) -> None: ...


class SampleRepository(Protocol):
    def add(self, sample: Sample) -> Sample: ...
    def get(self, sample_id: UUID) -> Sample | None: ...
    def list_by_manuscript(self, manuscript_id: UUID) -> list[Sample]: ...
    def update(self, sample: Sample) -> Sample: ...
    def delete(self, sample_id: UUID) -> None: ...


class EbookRepository(Protocol):
    def add(self, ebook: Ebook) -> Ebook: ...
    def get(self, ebook_id: UUID) -> Ebook | None: ...
    def list_by_manuscript(self, manuscript_id: UUID) -> list[Ebook]: ...
    def list_by_author(self, author_id: UUID) -> list[Ebook]: ...
    def update(self, ebook: Ebook) -> Ebook: ...
    def delete(self, ebook_id: UUID) -> None: ...
    def delete_by_manuscript(self, manuscript_id: UUID) -> None: ...


class DownloadRepository(Protocol):
    def add(self, download: Download) -> Download: ...
    def get(self, download_id: UUID) -> Download | None: ...
    def list_by_ebook(self, ebook_id: UUID) -> list[Download]: ...
    def count_by_ebook(self, ebook_id: UUID) -> int: ...
